# Generate the video script from the agent for the given topic

#     the prompt/script will be generated from the nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free by OpenRouter
#     User describe the video and the agent response with the script

# Importing all the libraries 
from langchain.chat_models import init_chat_model
from langchain.messages import HumanMessage, SystemMessage
from pathlib import Path
from model.utility.logging_config import setup_logging
from model.utility.load_envs import load_all_env
from model.utility.save_response import SaveLlmResponse
import http.client
import json
import os


class VideoAgent:
    """
    to generate the video agent we reuquired:
        1. Prompt/script of the video
        2. Brand logo (OPTIONAL)
        3. aspect ratio from generate script 
        4. feed these to the request method --POST to generate the video
        5. video generated
    """

    # load Openrouter API 
    OPENROUTER_API_KEY = load_all_env()[0]
    KIE_API_KEY = load_all_env()[1]


    def __init__(self, prompt_from_user, DEVMODE=True):
        
        
        # for development only, it will save the response to the json to reduce the token limits 
        self.DEVMODE=DEVMODE


        # setup the logger
        self.logger = setup_logging()


        # fetch and store the user input
        self.prompt_from_user = prompt_from_user

        # fetch the required files 
        self.prompts_dir = Path(__file__).resolve().parents[2] / "prompts"
        self.SYSTEM_VIDEO_PROMPT = self._load_prompt("script_video_prompt.md")
        self.TITLE_GENERATION_PROMPT = self._load_prompt("title_video_prompt.md")
        self._cached_script = None

    def _load_prompt(self, file_name: str) -> str:
        prompt_path = self.prompts_dir / file_name
        if not prompt_path.exists():
            raise FileNotFoundError(f"Prompt file not found: {prompt_path}")
        return prompt_path.read_text(encoding="utf-8")

    def _read_cached_data(self):
        read_data = SaveLlmResponse()
        cached_data = read_data.read_response()

        if isinstance(cached_data, dict) and cached_data:
            return cached_data

        if isinstance(cached_data, str):
            return cached_data

        return None

    @staticmethod
    def _base_agent_initializer(SYSTEM_MESSAGE: str, HUMAN_MESSAGE: str):
        '''
        Initialize the agent ..

        Args:
            SYSTEM_MESSAGE: str -> system prompt
            HUMAN_MESSAGE: str -> human entered message
        '''
        # Initialize the chat model
        model = init_chat_model(
            model="nvidia/nemotron-3-nano-30b-a3b:free",
            model_provider="openrouter",
        )    

        # initializee the system and the human message
        system_message = SystemMessage(SYSTEM_MESSAGE)
        human_message = HumanMessage(HUMAN_MESSAGE)
        messages = [system_message, human_message]

        response = model.invoke(messages)

        logger = setup_logging()

        logger.info(type(response))

        return response


    def video_generation_pompt(self) -> str:
        '''
        These will generate the video script based on the user requested video
            Returns:
                response : str : script generated by the agent for the requested video
        '''

        if self._cached_script is not None:
            return self._cached_script

        if self.DEVMODE:
            cached_data = self._read_cached_data()

            if isinstance(cached_data, dict) and cached_data.get("video_script"):
                self.logger.info("USING CACHED VIDEO SCRIPT FROM THE JSON FILE")
                self._cached_script = str(cached_data["video_script"])
                return self._cached_script

            if isinstance(cached_data, str) and cached_data != "No data found":
                self.logger.info("USING CACHED VIDEO SCRIPT FROM THE JSON FILE")
                self._cached_script = cached_data
                return cached_data

            self.logger.info("NO DATA FOUND FROM THE JSON FILE INVOKING THE AGENT ....")
            response = self._base_agent_initializer(SYSTEM_MESSAGE=self.SYSTEM_VIDEO_PROMPT, HUMAN_MESSAGE=self.prompt_from_user)
            self._cached_script = str(response.content)
            return self._cached_script

        else:
            response = self._base_agent_initializer(SYSTEM_MESSAGE=self.SYSTEM_VIDEO_PROMPT, HUMAN_MESSAGE=self.prompt_from_user)
            self._cached_script = str(response.content)
            return self._cached_script

        

    def ai_title_prompt(self) -> str:
        '''
        this will generate the title for the video 
        Returns:
            title_response.content : str : title generated from the video script
        '''

        # fetch the video script
        video_script = self.video_generation_pompt()

        
        if self.DEVMODE:
            cached_data = self._read_cached_data()

            if isinstance(cached_data, dict) and cached_data.get("title"):
                self.logger.info("PROCEEDING TO QUIT BECAUSE DATA IS THERE")
                return str(cached_data["title"])

            title_response = self._base_agent_initializer(
                SYSTEM_MESSAGE=self.TITLE_GENERATION_PROMPT,
                HUMAN_MESSAGE=f"generate the title for the video script {video_script}"
            )
            data = {
                "title": title_response.content,
                "video_script": video_script
            }
            save_data = SaveLlmResponse(data=data)
            save_data.write_data()
            self.logger.info("Data written successfully")
            return str(data['title'])

        else:
            title_response = self._base_agent_initializer(SYSTEM_MESSAGE=self.TITLE_GENERATION_PROMPT, HUMAN_MESSAGE=f"generate the title for the video script {video_script}")
            return str(title_response.content)

    @classmethod
    def _video_agent_initializor(cls, video_script, watermark=None, callback_url="http://your-callback-url.com/complete"):
        '''generate the video for the given script

        Args:
            video_script (str): a prompt for the video or the script 
            watermark (str): Default is None if configured then the watermark is applied to the video
            callback_url (str): a callback url to output the video on that URL
        '''

        conn = http.client.HTTPSConnection("api.kie.ai")
        payload = json.dumps({
        "prompt": video_script,
        "model": "veo3_fast",
        "watermark": watermark,
        "callBackUrl": "http://your-callback-url.com/complete",
        "aspect_ratio": "9:16", # prefered video output for the youtube...
        "enableFallback": False,
        "enableTranslation": False,
        "generationType": "TEXT_2_VIDEO"
        })
        print(cls.KIE_API_KEY)

        headers = {
        'Authorization': f'Bearer {cls.KIE_API_KEY}',
        'Content-Type': 'application/json'
        }
        conn.request("POST", "/api/v1/veo/generate", payload, headers)
        res = conn.getresponse()
        data = res.read()
        return data.decode("utf-8")

    def video_generator(self, watermark: str):
        '''call the video agent initializor to generate the video

        Args:
            watermark (str): watermarker for the video
        '''

        if self.DEVMODE:

            cache_data = self._read_cached_data()


            # parse the json data to the llm
            if isinstance(cache_data, dict):
                self.logger.info('(DEBUG MODE) LOADING THE CACHED DATA .... ')
                data = self._video_agent_initializor(video_script=cache_data.get('video_script'), watermark=watermark)
                return data 

            # if we do not have the cache data fetch it from the agent 
            video_script = self.video_generation_pompt()
            data = self._video_agent_initializor(video_script=video_script,watermark=watermark)
            return data

        else:
            # for production mode (DEBUG=False) 
            video_script = self.video_generation_pompt()
            
            # Video generation logic removed as requested for another technique
            self.logger.info("Video generation logic is disabled for DEVMODE=False.")
            return "Video generation skipped. Another technique will be used."