# Generate the video script from the agent for the given topic

#     the prompt/script will be generated from the nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free by OpenRouter
#     User describe the video and the agent response with the script

# Importing all the libraries 
from langchain.chat_models import init_chat_model
from langchain.messages import HumanMessage, SystemMessage
from pathlib import Path
from src.utility.logging_config import setup_logging
from src.utility.load_envs import load_all_env
from src.utility.save_response import SaveLlmResponse
import json



class VideoAgent:
    """
    to generate the video agent we reuquired:
        1. Prompt/script of the video
        2. Brand logo (OPTIONAL)
        3. aspect ratio from generate script 
        4. feed these to the request method --POST to generate the video
        5. video generated
    """

    # load Openrouter API 
    OPENROUTER_API_KEY = load_all_env()[0]


    def __init__(self, prompt_from_user, DEVMODE=True, open_router_model_name = None):
        
        
        # for development only, it will save the response to the json to reduce the token limits 
        self.DEVMODE=DEVMODE

        self.model_name = open_router_model_name


        # setup the logger
        self.logger = setup_logging()


        # fetch and store the user input
        self.prompt_from_user = prompt_from_user

        # fetch the required files 
        self.prompts_dir = Path(__file__).resolve().parents[3] / "prompts"
        self.SYSTEM_VIDEO_PROMPT = self._load_prompt("script_video_prompt.md")
        self.TITLE_GENERATION_PROMPT = self._load_prompt("title_video_prompt.md")

    def _load_prompt(self, file_name: str) -> str:
        prompt_path = self.prompts_dir / file_name
        if not prompt_path.exists():
            raise FileNotFoundError(f"Prompt file not found: {prompt_path}")
        return prompt_path.read_text(encoding="utf-8")

    def _read_cached_data(self):
        read_data = SaveLlmResponse()
        cached_data = read_data.read_response()

        if isinstance(cached_data, dict) and cached_data:
            return cached_data

        if isinstance(cached_data, str):
            return cached_data

        return None

    @staticmethod
    def _base_agent_initializer(SYSTEM_MESSAGE: str, HUMAN_MESSAGE: str, model_name = None):
        '''
        Initialize the agent ..

        Args:
            SYSTEM_MESSAGE: str -> system prompt
            HUMAN_MESSAGE: str -> human entered message
            model_name = OPen router valid model name
        '''

        if model_name == None:
            return 'set the open router model name first before generating content'

        # Initialize the chat model
        model = init_chat_model(
            model=model_name,
            model_provider="openrouter",
        )    

        # initializee the system and the human message
        system_message = SystemMessage(SYSTEM_MESSAGE)
        human_message = HumanMessage(HUMAN_MESSAGE)
        messages = [system_message, human_message]

        response = model.invoke(messages)


        return response


    def video_script_generator(self) -> dict:
        '''
        These will generate the video script based on the user requested video
            Returns:
                response : dict : script generated by the agent for the requested video
        '''

        if not self.DEVMODE:
            self.logger.info("In Devmode")
            cached_data = self._read_cached_data()


            if isinstance(cached_data, dict):
                self.logger.info("USING CACHED VIDEO SCRIPT FROM THE JSON FILE")
                script = cached_data['script_id']
                if isinstance(script, str):
                    try:
                        return json.loads(script)
                    except json.JSONDecodeError:
                        return script
                return script

            if isinstance(cached_data, str) and cached_data != "No data found":
                self.logger.info("USING CACHED VIDEO SCRIPT FROM THE JSON FILE")
                try:
                    return json.loads(cached_data)
                except json.JSONDecodeError:
                    return cached_data
            else:
                self.logger.info("NO DATA FOUND FROM THE JSON FILE INVOKING THE AGENT ....")
                response = self._base_agent_initializer(SYSTEM_MESSAGE=self.SYSTEM_VIDEO_PROMPT, HUMAN_MESSAGE=self.prompt_from_user, model_name=self.model_name)
                content = str(response.content).strip()
                if content.startswith("```json"):
                    content = content.split("```json")[1].rsplit("```", 1)[0].strip()
                elif content.startswith("```"):
                    content = content.split("```")[1].rsplit("```", 1)[0].strip()
                try:
                    return json.loads(content)
                except json.JSONDecodeError:
                    return {"error": "Failed to parse JSON", "raw_content": content}

        else:
            response = self._base_agent_initializer(SYSTEM_MESSAGE=self.SYSTEM_VIDEO_PROMPT, HUMAN_MESSAGE=self.prompt_from_user, model_name=self.model_name)
            content = str(response.content).strip()
            if content.startswith("```json"):
                content = content.split("```json")[1].rsplit("```", 1)[0].strip()
            elif content.startswith("```"):
                content = content.split("```")[1].rsplit("```", 1)[0].strip()
            try:
                save_response = SaveLlmResponse(data=json.loads(content))
                
                # write the data 
                response_status = save_response.write_data()
                self.logger.info("Script saved ....")
                return response_status
            except json.JSONDecodeError:
                return {"error": "Failed to parse JSON", "raw_content": content}