# Generate the video script from the agent for the given topic

#     the prompt/script will be generated from the nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free by OpenRouter
#     User describe the video and the agent response with the script

# Importing all the libraries 
from langchain.chat_models import init_chat_model
from langchain.messages import HumanMessage, SystemMessage
from pathlib import Path
from model.utility.logging_config import setup_logging
from model.utility.load_envs import load_all_env
from model.utility.save_response import SaveLlmResponse
import http.client
import json
import os


class VideoAgent:
    """
    to generate the video agent we reuquired:
        1. Prompt/script of the video
        2. Brand logo (OPTIONAL)
        3. aspect ratio from generate script 
        4. feed these to the request method --POST to generate the video
        5. video generated
    """

    # load Openrouter API 
    OPENROUTER_API_KEY = load_all_env()[0]


    def __init__(self, prompt_from_user, DEVMODE=True):
        
        
        # for development only, it will save the response to the json to reduce the token limits 
        self.DEVMODE=DEVMODE


        # setup the logger
        self.logger = setup_logging()


        # fetch and store the user input
        self.prompt_from_user = prompt_from_user

        # fetch the required files 
        self.prompts_dir = Path(__file__).resolve().parents[2] / "prompts"
        self.SYSTEM_VIDEO_PROMPT = self._load_prompt("script_video_prompt.md")
        self.TITLE_GENERATION_PROMPT = self._load_prompt("title_video_prompt.md")

    def _load_prompt(self, file_name: str) -> str:
        prompt_path = self.prompts_dir / file_name
        if not prompt_path.exists():
            raise FileNotFoundError(f"Prompt file not found: {prompt_path}")
        return prompt_path.read_text(encoding="utf-8")

    def _read_cached_data(self):
        read_data = SaveLlmResponse()
        cached_data = read_data.read_response()

        if isinstance(cached_data, dict) and cached_data:
            return cached_data

        if isinstance(cached_data, str):
            return cached_data

        return None

    @staticmethod
    def _base_agent_initializer(SYSTEM_MESSAGE: str, HUMAN_MESSAGE: str):
        '''
        Initialize the agent ..

        Args:
            SYSTEM_MESSAGE: str -> system prompt
            HUMAN_MESSAGE: str -> human entered message
        '''
        # Initialize the chat model
        model = init_chat_model(
            model="nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
            model_provider="openrouter",
        )    

        # initializee the system and the human message
        system_message = SystemMessage(SYSTEM_MESSAGE)
        human_message = HumanMessage(HUMAN_MESSAGE)
        messages = [system_message, human_message]

        response = model.invoke(messages)


        return response


    def video_script_generator(self) -> dict:
        '''
        These will generate the video script based on the user requested video
            Returns:
                response : dict : script generated by the agent for the requested video
        '''

        if self.DEVMODE:
            cached_data = self._read_cached_data()

            if isinstance(cached_data, dict) and cached_data.get("video_script"):
                self.logger.info("USING CACHED VIDEO SCRIPT FROM THE JSON FILE")
                script = cached_data["video_script"]
                if isinstance(script, str):
                    try:
                        return json.loads(script)
                    except json.JSONDecodeError:
                        return script
                return script

            if isinstance(cached_data, str) and cached_data != "No data found":
                self.logger.info("USING CACHED VIDEO SCRIPT FROM THE JSON FILE")
                try:
                    return json.loads(cached_data)
                except json.JSONDecodeError:
                    return cached_data

            self.logger.info("NO DATA FOUND FROM THE JSON FILE INVOKING THE AGENT ....")
            response = self._base_agent_initializer(SYSTEM_MESSAGE=self.SYSTEM_VIDEO_PROMPT, HUMAN_MESSAGE=self.prompt_from_user)
            content = str(response.content).strip()
            if content.startswith("```json"):
                content = content.split("```json")[1].rsplit("```", 1)[0].strip()
            elif content.startswith("```"):
                content = content.split("```")[1].rsplit("```", 1)[0].strip()
            try:
                return json.loads(content)
            except json.JSONDecodeError:
                return {"error": "Failed to parse JSON", "raw_content": content}

        else:
            response = self._base_agent_initializer(SYSTEM_MESSAGE=self.SYSTEM_VIDEO_PROMPT, HUMAN_MESSAGE=self.prompt_from_user)
            content = str(response.content).strip()
            if content.startswith("```json"):
                content = content.split("```json")[1].rsplit("```", 1)[0].strip()
            elif content.startswith("```"):
                content = content.split("```")[1].rsplit("```", 1)[0].strip()
            try:
                return json.loads(content)
            except json.JSONDecodeError:
                return {"error": "Failed to parse JSON", "raw_content": content}

        

    def ai_title_prompt(self, video_script: dict | str) -> str:
        '''this will generate the title for the video 

        Args:
            video_script (dict | str): the script of the video 
        Returns:
            title_response.content : str : title generated from the video script
        '''
        
        if self.DEVMODE:
            cached_data = self._read_cached_data()

            if isinstance(cached_data, dict) and cached_data.get("title"):
                self.logger.info("PROCEEDING TO QUIT BECAUSE DATA IS THERE")
                return str(cached_data["title"])

            script_str = json.dumps(video_script) if isinstance(video_script, dict) else str(video_script)
            title_response = self._base_agent_initializer(
                SYSTEM_MESSAGE=self.TITLE_GENERATION_PROMPT,
                HUMAN_MESSAGE=f"generate the title for the video script {script_str}"
            )
            data = {
                "title": title_response.content,
                "video_script": video_script
            }
            save_data = SaveLlmResponse(data=data)
            save_data.write_data()
            self.logger.info("Data written successfully")
            return str(data['title'])

        else:
            script_str = json.dumps(video_script) if isinstance(video_script, dict) else str(video_script)
            title_response = self._base_agent_initializer(SYSTEM_MESSAGE=self.TITLE_GENERATION_PROMPT, HUMAN_MESSAGE=f"generate the title for the video script {script_str}")
            return str(title_response.content)        