# Generate the video script from the agent for the given topic

#     the prompt/script will be generated from the nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free by OpenRouter
#     User describe the video and the agent response with the script

# Importing all the libraries 
from langchain.agents import create_agent
from langchain.chat_models import init_chat_model
from langchain.messages import HumanMessage, AIMessage, SystemMessage
from model.utility.load_envs import load_all_env


# load Openrouter API 
OPENROUTER_API_KEY = load_all_env()
OPENROUTER_API_KEY = OPENROUTER_API_KEY[0]


# Building up the prompt 
model = init_chat_model(
    model="nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    model_provider="openrouter",
)

def ai_video_prompt(prompt_from_user: str, SYSTEM_VIDEO_PROMPT: str) -> str:
    '''
    These will generate the video script based on the user requested video
    Args:
        prompt_from_user: str : get the user query
    
        Returns:
            response.content : str : script generated by the agent for the requested video
    '''
    
    
    # Initializing system-message 
    system_message = SystemMessage(
        str(SYSTEM_VIDEO_PROMPT)
    )
    human_message = HumanMessage(prompt_from_user)

    # use with chat's models 
    messages = [system_message, human_message]
    response = model.invoke(messages)
    return response.content

