# Generate the video script from the agent for the given topic

#     the prompt/script will be generated from the nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free by OpenRouter
#     User describe the video and the agent response with the script

# Importing all the libraries 
from langchain.agents import create_agent
from langchain.chat_models import init_chat_model
from langchain.messages import HumanMessage, AIMessage, SystemMessage
from model.utility.load_envs import load_all_env
from pathlib import Path


class PromptAgent:

    # load Openrouter API 
    OPENROUTER_API_KEY = load_all_env()
    OPENROUTER_API_KEY = OPENROUTER_API_KEY[0]

    def __init__(self, prompt_from_user):
        
        # Initilize the chat model
        self.model = init_chat_model(
            model="nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
            model_provider="openrouter",
        )

        self.prompt_from_user = prompt_from_user
        self.prompts_dir = Path(__file__).resolve().parents[2] / "prompts"
        self.SYSTEM_VIDEO_PROMPT = self._load_prompt("script_video_prompt.md")
        self.TITLE_GENERATION_PROMPT = self._load_prompt("title_video_prompt.md")

    def _load_prompt(self, file_name: str) -> str:
        prompt_path = self.prompts_dir / file_name
        if not prompt_path.exists():
            raise FileNotFoundError(f"Prompt file not found: {prompt_path}")
        return prompt_path.read_text(encoding="utf-8")


    def ai_video_prompt(self) -> str:
        '''
        These will generate the video script based on the user requested video
            Returns:
                response.content : str : script generated by the agent for the requested video
        '''
        
        
        # Initializing system-message 
        system_message = SystemMessage(
            self.SYSTEM_VIDEO_PROMPT
        )
        human_message = HumanMessage(self.prompt_from_user)

        # use with chat's models 
        messages = [system_message, human_message]
        response = self.model.invoke(messages)
        return response.content

    def ai_title_prompt(self) -> str:
        '''
        this will generate the title for the video 
        Returns:
            title_response.content : str : title generated from the video script
        '''

        # fetch the video script
        video_script = self.ai_video_prompt()

        # initialize the messages 
        system_message = SystemMessage(
            self.TITLE_GENERATION_PROMPT
        )

        human_message = f"based on the {video_script} generate the title"

        messages = [system_message, human_message]

        title_response = self.model.invoke(messages)

        print(video_script)
        print(10 * "*")

        return title_response.content

